function [coord, coord_idx, color, color_idx, normal, normal_idx] = parseVrml(filename)

%Parses VRML 2.0 (97) files generated by Solidworks
%used to generate patch object

fid = fopen(filename,'r');

tmp = ' ';

coord = cell(1);
coord_idx = cell(1);
color = cell(1);
color_idx = cell(1);
normal = cell(1);
normal_idx = cell(1);

pno = 0; %part number

while tmp ~= -1
    tmp = fgets(fid); % -1 if eof
    if ~isempty(strfind(tmp,'color ['))
        pno = pno + 1;
        numstr = getNumStr(fid);
        M = str2num(numstr); %#ok<*ST2NM>
        color{pno} = reshape(M,3,length(M)/3)'; %nx3 matrix
    end
    
    if ~isempty(strfind(tmp,'point ['))
        numstr = getNumStr(fid);
        M = str2num(numstr);
        coord{pno} = reshape(M,3,length(M)/3)'; %nx3 matrix
    end
    
    if ~isempty(strfind(tmp,'vector ['))
        numstr = getNumStr(fid);
        M = str2num(numstr);
        normal{pno} = reshape(M,3,length(M)/3)'; %nx3 matrix
    end
    
    %note, we add 1 because MATLAB indexing starts at 1 not 0!
    if ~isempty(strfind(tmp,'coordIndex ['))
        numstr = getNumStr(fid);
        M = str2num(numstr);
        coord_idx{pno} = reshape(M,4,length(M)/4)'; %nx4 matrix
        coord_idx{pno} = coord_idx{pno}(:,1:3); %remove column of -1s
        coord_idx{pno} = coord_idx{pno}+1;
    end
    
    if ~isempty(strfind(tmp,'colorIndex ['))
        numstr = getNumStr(fid);
        M = str2num(numstr);
        color_idx{pno} = M'; %nx1 vector
        color_idx{pno} = color_idx{pno}+1;
    end
    
    if ~isempty(strfind(tmp,'normalIndex ['))
        numstr = getNumStr(fid);
        M = str2num(numstr);
        normal_idx{pno} = reshape(M,4,length(M)/4)'; %nx4 matrix
        normal_idx{pno} = normal_idx{pno}(:,1); %only need the first column, normal is the same for all vertices in triangle
        normal_idx{pno} = normal_idx{pno}+1;
    end
    
end

fclose(fid);

%make color index if necessary (all ones)
for pno = 1:length(color)
    if isempty(color_idx{pno}) 
        nt = size(coord_idx{pno},1);
        color_idx{pno} = ones(nt,1);
    end
end

end

function numstr = getNumStr(fid)
    %reads & appends lines from file until line contains a bracket ']'

    numstr=[]; %numeric string, in brackets
    while 1
        tmp = fgets(fid);
        if ~isempty(strfind(tmp,']'))
            break
        end
        numstr = [numstr, tmp]; %#ok<AGROW>
    end
    numstr = strrep(numstr,[char(13) char(10)],''); %remove [carriage return, new line]
    numstr = strrep(numstr,',',''); %remove commas
end


